#!/usr/bin/env ruby

$ << "(DATADIR)/dwm_edje/"

require 'Launcher'
require 'optparse'

@config = {}

ARGV.options do |opts|
   opts.on("-h", "--help", "Print this text") { puts opts; exit }
   opts.on("-g", "--geometry WIDTHxHEIGHT", "Set size") { |x| @config[:geo] = x.split('x').collect { |s| s.to_i } if x =~ /^\d+x\d+$/ } 
   opts.on("-f", "--fullscreen", "Enable fullscreen") { %x[xrandr][/ *(\d+x\d+).*\*/]; @config[:geo] = $1.split('x').collect { |s| s.to_i } }
   opts.on("-d", "--desktop-directories [PATH,PATH]", Array, "Set application's *.desktop files paths") { |paths| @config[:paths] = paths } 
   opts.parse!
end   

la = Launcher.new(@config)
la.add_run_parts("utilities")
#8.times { |x| la.add_spotlight_signal("kata"+(x+2).to_s, x)}
la.show
